model_path: "models/happysad.emfmodel"
labels:
  0: "neutral"
  1: "excited"
  2: "sad"
sample_count: 500
sample_len: 1.5
random_seed: "amogus"
dataset: "./dataset/"
tmp: "./tmp/"
paramprefix: "/avatar/parameters/EmoFlow/"
fs: 44100
window: 5